[build]
  command = "npm run build && cp public/_redirects dist/ && cp public/static.html dist/404.html"
  publish = "dist"

# Redirect root path explicitly
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Redirect all other paths
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

