[build]
  command = "./build.sh"
  publish = "dist"

# Redirect root path explicitly
[[redirects]]
  from = "/"
  to = "/index.html"
  status = 200

# Redirect all other paths
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

